# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test_selection_type',
            field=models.CharField(
                blank=True,
                choices=[('all', 'All Tests'), ('folder', 'By Folders'), ('specific', 'Specific Test Cases')],
                help_text='How tests are selected for execution',
                max_length=20,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='selected_folders',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of folder IDs when test_selection_type is 'folder'"
            ),
        ),
    ]