# Generated by Django 4.2.10 on 2025-06-01 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("testcases", "0004_testcase_estimated_time"),
        ("events", "0002_add_test_selection_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date", "time"]},
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="events_event_priorit_7a1097_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_date_5e8e1c_idx",
            old_name="events_event_date_b64c8b_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_event_t_a87b5c_idx",
            old_name="events_event_event_t_34da7e_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_created_95418c_idx",
            old_name="events_event_created_ee8f57_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_project_1adb21_idx",
            old_name="events_event_project_3b0ec3_idx",
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("general", "General Event"),
                    ("test-execution", "Test Execution"),
                    ("maintenance", "Maintenance"),
                    ("meeting", "Meeting"),
                    ("deadline", "Deadline"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="recurrence_interval",
            field=models.PositiveIntegerField(
                blank=True, help_text="Repeat every X periods", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="recurrence_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "Month"),
                    ("year", "Year"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="test_cases",
            field=models.ManyToManyField(blank=True, to="testcases.testcase"),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
