# Generated by Django 4.2.10 on 2025-05-15 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("automation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Unnamed Test Case",
                        help_text="Title of the test case",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the test case",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the test case was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the test case was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        help_text="Preconditions required for the test case",
                        null=True,
                        verbose_name="Preconditions",
                    ),
                ),
                (
                    "steps",
                    models.TextField(
                        blank=True,
                        help_text="Steps to follow for the test case",
                        null=True,
                        verbose_name="Test steps",
                    ),
                ),
                (
                    "expected_results",
                    models.TextField(
                        blank=True,
                        help_text="Expected results of the test case",
                        null=True,
                        verbose_name="Expected results",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        help_text="Priority level of the test case",
                        max_length=50,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        default="Any",
                        help_text="Platform or environment for the test case",
                        max_length=50,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automated", "Automated")],
                        default="manual",
                        help_text="Type of test case (manual or automated)",
                        max_length=50,
                        verbose_name="Test type",
                    ),
                ),
                (
                    "test_code",
                    models.TextField(
                        blank=True,
                        help_text="Source code for automated tests",
                        null=True,
                        verbose_name="Test code",
                    ),
                ),
                (
                    "script_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the test script file",
                        max_length=255,
                        null=True,
                        verbose_name="Script path",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test class",
                        max_length=255,
                        null=True,
                        verbose_name="Class name",
                    ),
                ),
                (
                    "method_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test method",
                        max_length=255,
                        null=True,
                        verbose_name="Method name",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pytest", "PyTest"),
                            ("unittest", "UnitTest"),
                            ("robot", "Robot Framework"),
                            ("cypress", "Cypress"),
                            ("selenium", "Selenium"),
                            ("playwright", "Playwright"),
                            ("other", "Other"),
                        ],
                        default="pytest",
                        help_text="Test framework used",
                        max_length=50,
                        null=True,
                        verbose_name="Framework",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing the test case",
                        null=True,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that created this test case",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "automation_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Automation project that this test case belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_cases",
                        to="automation.automationproject",
                        verbose_name="Automation project",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Folder containing this test case",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_cases",
                        to="projects.folder",
                        verbose_name="Folder",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that this test case belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "test case",
                "verbose_name_plural": "test cases",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("skipped", "Skipped"),
                            ("in_progress", "In Progress"),
                        ],
                        default="in_progress",
                        help_text="Status of the test execution",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "execution_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the test was executed",
                        verbose_name="Execution date",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True,
                        help_text="Time taken to execute the test",
                        null=True,
                        verbose_name="Execution time",
                    ),
                ),
                (
                    "actual_result",
                    models.TextField(
                        blank=True,
                        help_text="Actual result of the test execution",
                        null=True,
                        verbose_name="Actual result",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Additional comments about the test execution",
                        null=True,
                        verbose_name="Comments",
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        help_text="Attachments related to the test execution",
                        null=True,
                        upload_to="test_reports/",
                        verbose_name="Attachments",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        help_text="Environment where the test was executed",
                        max_length=255,
                        null=True,
                        verbose_name="Environment",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the software being tested",
                        max_length=50,
                        null=True,
                        verbose_name="Version",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for batch reports",
                        max_length=50,
                        null=True,
                        verbose_name="Report ID",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        help_text="User that executed the test",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Executor",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        help_text="Test case that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="testcases.testcase",
                        verbose_name="Test case",
                    ),
                ),
            ],
            options={
                "verbose_name": "test report",
                "verbose_name_plural": "test reports",
                "ordering": ["-execution_date"],
            },
        ),
        migrations.CreateModel(
            name="TestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("start", "Test Started"),
                            ("step_complete", "Step Completed"),
                            ("error", "Error Occurred"),
                            ("warning", "Warning"),
                            ("info", "Information"),
                            ("finish", "Test Finished"),
                        ],
                        help_text="Type of event",
                        max_length=50,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the event occurred",
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the event", verbose_name="Description"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="Additional details about the event in JSON format",
                        null=True,
                        verbose_name="Details",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="info",
                        help_text="Severity level of the event",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Screenshot related to the event",
                        null=True,
                        upload_to="test_events/screenshots/",
                        verbose_name="Screenshot",
                    ),
                ),
                (
                    "log_file",
                    models.FileField(
                        blank=True,
                        help_text="Log file related to the event",
                        null=True,
                        upload_to="test_events/logs/",
                        verbose_name="Log file",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User that created this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_test_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        help_text="Test case related to this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="testcases.testcase",
                        verbose_name="Test case",
                    ),
                ),
                (
                    "test_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Test report related to this event",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="testcases.testreport",
                        verbose_name="Test report",
                    ),
                ),
            ],
            options={
                "verbose_name": "test event",
                "verbose_name_plural": "test events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        help_text="Current status of the test run",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="Date and time when the test run started",
                        null=True,
                        verbose_name="Started at",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        help_text="Date and time when the test run finished",
                        null=True,
                        verbose_name="Finished at",
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        help_text="Duration of the test run in seconds",
                        null=True,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the test run failed",
                        null=True,
                        verbose_name="Error message",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Output from the test run",
                        null=True,
                        verbose_name="Output",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for batch test runs",
                        max_length=50,
                        null=True,
                        verbose_name="Run ID",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        help_text="User that executed the test run",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Executor",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        help_text="Test case that was executed",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="testcases.testcase",
                        verbose_name="Test case",
                    ),
                ),
            ],
            options={
                "verbose_name": "test run",
                "verbose_name_plural": "test runs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["test_case", "status"],
                        name="testcases_t_test_ca_f83fde_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="testcases_t_started_338b1e_idx"
                    ),
                    models.Index(
                        fields=["run_id"], name="testcases_t_run_id_d12492_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="testreport",
            index=models.Index(
                fields=["test_case", "status"], name="testcases_t_test_ca_510cd8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testreport",
            index=models.Index(
                fields=["execution_date"], name="testcases_t_executi_f4a4e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testreport",
            index=models.Index(
                fields=["report_id"], name="testcases_t_report__61d0e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testevent",
            index=models.Index(
                fields=["timestamp"], name="testcases_t_timesta_4263c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testevent",
            index=models.Index(
                fields=["event_type"], name="testcases_t_event_t_94e087_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testevent",
            index=models.Index(
                fields=["severity"], name="testcases_t_severit_520fe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["project"], name="testcases_t_project_bd512e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["folder"], name="testcases_t_folder__a13714_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["priority"], name="testcases_t_priorit_65378a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["test_type"], name="testcases_t_test_ty_cbfc62_idx"
            ),
        ),
    ]
