# Generated by Django 4.2.10 on 2025-05-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testcases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="automation_test_name",
            field=models.CharField(
                blank=True,
                help_text="Full name of the automation test in the repository (e.g., tests/test_login.py::TestLogin::test_successful_login)",
                max_length=500,
                null=True,
                verbose_name="Automation test name",
            ),
        ),
    ]
