# Generated by Django 4.2.10 on 2025-05-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0002_initial"),
        ("testcases", "0002_testcase_automation_test_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="automation_test",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked automation test from repository",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_test_cases",
                to="automation.automationtest",
            ),
        ),
    ]
