# Generated by Django 4.2.10 on 2025-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testcases", "0003_testcase_automation_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="estimated_time",
            field=models.CharField(
                blank=True,
                help_text="Estimated time for test execution",
                max_length=100,
                null=True,
                verbose_name="Estimated time",
            ),
        ),
    ]
