# Generated by Django 4.2.10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('testcases', '0004_testcase_estimated_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the regression run', max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the regression run was created', verbose_name='Created at')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the regression run was started', null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the regression run was completed', null=True, verbose_name='Completed at')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Current status of the regression run', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Description of the regression run', null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(help_text='User who created this regression run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regression_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this regression run belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='regression_runs', to='projects.project')),
                ('test_cases', models.ManyToManyField(help_text='Test cases included in this regression run', related_name='regression_runs', to='testcases.testcase')),
            ],
            options={
                'verbose_name': 'regression run',
                'verbose_name_plural': 'regression runs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['project', 'status'], name='testcases_r_project_a4de6f_idx'),
                    models.Index(fields=['created_at'], name='testcases_r_created_0f7a8f_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='testrun',
            name='run_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='automated', help_text='Type of test run (manual or automated)', max_length=20, verbose_name='Run type'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='regression_run',
            field=models.ForeignKey(blank=True, help_text='Regression run this test is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='testcases.regressionrun'),
        ),
    ]