# Generated by Django 4.2.10 on 2025-06-07 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testcases", "0005_add_regression_testing"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="regressionrun",
            new_name="testcases_r_project_7236c6_idx",
            old_name="testcases_r_project_a4de6f_idx",
        ),
        migrations.RenameIndex(
            model_name="regressionrun",
            new_name="testcases_r_created_8e884d_idx",
            old_name="testcases_r_created_0f7a8f_idx",
        ),
    ]
