# Generated by Django 4.2.10 on 2025-05-15 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the report template",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the report template",
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the template was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the template was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the template has been deleted (soft delete)",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration of the report template in JSON format",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template for the project",
                        verbose_name="Is default",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User that created this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that this template belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "report template",
                "verbose_name_plural": "report templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the report",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the report",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the report was generated",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Generated report file",
                        null=True,
                        upload_to="reports/",
                        verbose_name="File",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                        ],
                        default="html",
                        help_text="Format of the generated report",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Parameters used to generate the report",
                        verbose_name="Parameters",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this report is marked as a favorite",
                        verbose_name="Is favorite",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User that generated this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that this report belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template used to generate this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to="reports.reporttemplate",
                        verbose_name="Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "generated report",
                "verbose_name_plural": "generated reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the chart",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the chart",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("doughnut", "Doughnut Chart"),
                            ("radar", "Radar Chart"),
                            ("polarArea", "Polar Area Chart"),
                            ("bubble", "Bubble Chart"),
                            ("scatter", "Scatter Chart"),
                        ],
                        help_text="Type of chart to display",
                        max_length=50,
                        verbose_name="Chart type",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("test_status", "Test Status"),
                            ("user_activity", "User Activity"),
                            ("daily_trends", "Daily Trends"),
                            ("custom_query", "Custom Query"),
                            ("test_execution_time", "Test Execution Time"),
                            ("test_failures", "Test Failures"),
                            ("test_priority", "Test Priority"),
                        ],
                        help_text="Source of data for the chart",
                        max_length=50,
                        verbose_name="Data source",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Chart-specific configuration in JSON format",
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "custom_query",
                    models.TextField(
                        blank=True,
                        help_text="SQL query for custom data source",
                        null=True,
                        verbose_name="Custom query",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the chart was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the chart was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the chart is public (visible to all project members)",
                        verbose_name="Is public",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User that created this chart",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_charts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that this chart belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_charts",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "custom chart",
                "verbose_name_plural": "custom charts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SchedulerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the event",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the event",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("run_tests", "Run Tests"),
                            ("generate_report", "Generate Report"),
                            ("general", "General Event"),
                        ],
                        default="general",
                        help_text="Type of event to schedule",
                        max_length=50,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        help_text="Date and time when the event is scheduled",
                        verbose_name="Scheduled time",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="none",
                        help_text="Recurrence pattern for the event",
                        max_length=50,
                        verbose_name="Recurrence",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        help_text="Configuration for the event in JSON format",
                        null=True,
                        verbose_name="Configuration",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the event was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the event was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the event was last executed",
                        null=True,
                        verbose_name="Last run",
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the event will be executed next",
                        null=True,
                        verbose_name="Next run",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the event",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User that created this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scheduler_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent event that generated this event",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_events",
                        to="reports.schedulerevent",
                        verbose_name="Parent event",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "scheduler event",
                "verbose_name_plural": "scheduler events",
                "ordering": ["scheduled_time"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_time"], name="reports_sch_schedul_0f24b6_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="reports_sch_event_t_3c8ddf_idx"
                    ),
                    models.Index(
                        fields=["status"], name="reports_sch_status_d5301a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["project", "is_default"], name="reports_rep_project_cd5ed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["is_deleted"], name="reports_rep_is_dele_f22810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["project", "created_at"], name="reports_gen_project_49e77f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(fields=["format"], name="reports_gen_format_957082_idx"),
        ),
        migrations.AddIndex(
            model_name="customchart",
            index=models.Index(
                fields=["project", "chart_type"], name="reports_cus_project_977c85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customchart",
            index=models.Index(
                fields=["data_source"], name="reports_cus_data_so_58b30f_idx"
            ),
        ),
    ]
