# Generated by Django 4.2.10 on 2025-05-15 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the automation project",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "repository_url",
                    models.URLField(
                        help_text="URL of the repository containing the automated tests",
                        verbose_name="Repository URL",
                    ),
                ),
                (
                    "repository_type",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                        ],
                        default="github",
                        help_text="Type of the repository",
                        max_length=20,
                        verbose_name="Repository type",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        default="main",
                        help_text="Branch of the repository to use",
                        max_length=100,
                        verbose_name="Branch",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-detect"),
                            ("pytest", "PyTest"),
                            ("unittest", "UnitTest"),
                            ("robot", "Robot Framework"),
                            ("playwright", "Playwright"),
                        ],
                        default="auto",
                        help_text="Test framework used in the repository",
                        max_length=20,
                        verbose_name="Framework",
                    ),
                ),
                (
                    "tests_directory",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Directory in the repository containing the tests",
                        max_length=255,
                        verbose_name="Tests directory",
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        blank=True,
                        help_text="Local path where the repository is cloned",
                        max_length=255,
                        null=True,
                        verbose_name="Local path",
                    ),
                ),
                (
                    "detected_frameworks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of frameworks detected in the repository",
                        null=True,
                        verbose_name="Detected frameworks",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        help_text="Personal access token for private repositories",
                        max_length=255,
                        null=True,
                        verbose_name="Access token",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username for private repositories",
                        max_length=100,
                        null=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the repository was last synchronized",
                        null=True,
                        verbose_name="Last sync",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time when the automation project was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the automation project was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("not_synced", "Not Synced"),
                            ("error", "Error"),
                            ("syncing", "Syncing"),
                        ],
                        default="not_synced",
                        help_text="Current synchronization status",
                        max_length=20,
                        verbose_name="Sync status",
                    ),
                ),
                (
                    "sync_message",
                    models.TextField(
                        blank=True,
                        help_text="Message from the last synchronization attempt",
                        null=True,
                        verbose_name="Sync message",
                    ),
                ),
            ],
            options={
                "verbose_name": "automation project",
                "verbose_name_plural": "automation projects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AutomationTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the test",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path to the test file in the repository",
                        max_length=255,
                        verbose_name="File path",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test class",
                        max_length=255,
                        null=True,
                        verbose_name="Class name",
                    ),
                ),
                (
                    "method_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the test method",
                        max_length=255,
                        null=True,
                        verbose_name="Method name",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the test is available for execution",
                        verbose_name="Is available",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the test was last executed",
                        null=True,
                        verbose_name="Last run",
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        help_text="Status of the last test execution",
                        max_length=50,
                        null=True,
                        verbose_name="Last status",
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("pytest", "PyTest"),
                            ("unittest", "UnitTest"),
                            ("robot", "Robot Framework"),
                            ("playwright", "Playwright"),
                            ("other", "Other"),
                        ],
                        default="pytest",
                        help_text="Test framework used for this test",
                        max_length=20,
                        verbose_name="Framework",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the test extracted from docstrings or comments",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parameters required for the test",
                        null=True,
                        verbose_name="Parameters",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags associated with the test",
                        null=True,
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "automation test",
                "verbose_name_plural": "automation tests",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        help_text="Current status of the execution",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the execution started",
                        null=True,
                        verbose_name="Start time",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the execution ended",
                        null=True,
                        verbose_name="End time",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Duration of the execution",
                        null=True,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Result of the execution",
                        null=True,
                        verbose_name="Result",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the execution failed",
                        null=True,
                        verbose_name="Error message",
                    ),
                ),
                (
                    "logs",
                    models.TextField(
                        blank=True,
                        help_text="Logs of the execution",
                        null=True,
                        verbose_name="Logs",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        default="default",
                        help_text="Environment in which the test was executed",
                        max_length=100,
                        verbose_name="Environment",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parameters used for the execution",
                        null=True,
                        verbose_name="Parameters",
                    ),
                ),
                (
                    "artifacts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Artifacts produced by the execution (screenshots, files, etc.)",
                        null=True,
                        verbose_name="Artifacts",
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True,
                        help_text="Output of the execution (stdout/stderr)",
                        null=True,
                        verbose_name="Output",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the execution record was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the execution record was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "test execution",
                "verbose_name_plural": "test executions",
                "ordering": ["-start_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the schedule",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the schedule",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "schedule_time",
                    models.TimeField(
                        help_text="Time of day when the tests should be executed",
                        verbose_name="Schedule time",
                    ),
                ),
                (
                    "schedule_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days of the week when the tests should be executed (0-6 for Monday-Sunday)",
                        null=True,
                        verbose_name="Schedule days",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="none",
                        help_text="Recurrence pattern for the schedule",
                        max_length=20,
                        verbose_name="Recurrence",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the schedule is active",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the tests were last executed",
                        null=True,
                        verbose_name="Last run",
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the tests will be executed next",
                        null=True,
                        verbose_name="Next run",
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        help_text="Status of the last scheduled execution",
                        max_length=20,
                        verbose_name="Last status",
                    ),
                ),
                (
                    "last_result",
                    models.TextField(
                        blank=True,
                        help_text="Result of the last scheduled execution",
                        verbose_name="Last result",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the schedule was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the schedule was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "notification_emails",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Email addresses to notify about schedule execution results",
                        null=True,
                        verbose_name="Notification emails",
                    ),
                ),
            ],
            options={
                "verbose_name": "test schedule",
                "verbose_name_plural": "test schedules",
                "ordering": ["schedule_time", "name"],
            },
        ),
    ]
