# Generated by Django 4.2.10 on 2025-05-15 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("automation", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testschedule",
            name="created_by",
            field=models.ForeignKey(
                help_text="User that created this schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="testschedule",
            name="project",
            field=models.ForeignKey(
                help_text="Automation project that this schedule belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="automation.automationproject",
                verbose_name="Automation project",
            ),
        ),
        migrations.AddField(
            model_name="testschedule",
            name="tests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tests to be executed according to this schedule",
                related_name="schedules",
                to="automation.automationtest",
                verbose_name="Tests",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="automation_test",
            field=models.ForeignKey(
                help_text="Automation test associated with this execution",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="automation.automationtest",
                verbose_name="Automation test",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="scheduled_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Schedule that triggered this execution, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="automation.testschedule",
                verbose_name="Scheduled run",
            ),
        ),
        migrations.AddField(
            model_name="testexecution",
            name="triggered_by",
            field=models.ForeignKey(
                help_text="User that triggered this execution",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_executions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Triggered by",
            ),
        ),
        migrations.AddField(
            model_name="automationtest",
            name="project",
            field=models.ForeignKey(
                help_text="Automation project that this test belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="automation.automationproject",
                verbose_name="Automation project",
            ),
        ),
        migrations.AddField(
            model_name="automationproject",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project that this automation project belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_projects",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="automationtest",
            unique_together={("project", "file_path", "class_name", "method_name")},
        ),
        migrations.AlterUniqueTogether(
            name="automationproject",
            unique_together={("name", "project")},
        ),
    ]
