# Generated by Django 4.2.10 on 2025-05-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationproject",
            name="repository_url",
            field=models.CharField(
                help_text="URL of the repository containing the automated tests",
                max_length=500,
                verbose_name="Repository URL",
            ),
        ),
    ]
