# Generated by Django 4.2.10 on 2025-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_customuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="System role that cannot be deleted"
            ),
        ),
    ]
