# Generated by Django 4.2.10 on 2025-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_role_is_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("profile_update", "Profile Update"),
                    ("password_change", "Password Change"),
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("test_case_create", "Test Case Created"),
                    ("test_case_update", "Test Case Updated"),
                    ("test_case_delete", "Test Case Deleted"),
                    ("test_run", "Test Run"),
                    ("report_generate", "Report Generated"),
                    ("event_create", "Event Created"),
                    ("event_update", "Event Updated"),
                    ("event_delete", "Event Deleted"),
                ],
                max_length=50,
            ),
        ),
    ]
